import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  // هواتف ذكية
  {
    id: '1',
    name: 'آيفون 15 برو ماكس',
    description: 'أحدث هاتف من آبل مع معالج A17 Pro وكاميرا احترافية تمنحك صوراً مذهلة في كافة ظروف الإضاءة.',
    price: 4999,
    discountPrice: 4699,
    category: 'هواتف ذكية',
    images: ['https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    createdAt: Date.now(),
  },
  {
    id: '2',
    name: 'سامسونج S24 ألترا',
    description: 'هاتف سامسونج الرائد مع ميزات الذكاء الاصطناعي المتقدمة وقلم S Pen المدمج وشاشة سطوع هائل.',
    price: 5299,
    category: 'هواتف ذكية',
    images: ['https://images.unsplash.com/photo-1707065091321-43e59276f7c9?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    createdAt: Date.now(),
  },
  {
    id: 'p-phone-3',
    name: 'جوجل بيكسل 8 برو',
    description: 'تجربة أندرويد الخام مع أفضل كاميرا ذكاء اصطناعي في السوق.',
    price: 3899,
    category: 'هواتف ذكية',
    images: ['https://images.unsplash.com/photo-1697522502800-4740e53a55cd?auto=format&fit=crop&q=80&w=800'],
    stock: 7,
    createdAt: Date.now(),
  },

  // أجهزة كمبيوتر
  {
    id: '4',
    name: 'ماك بوك إير M3',
    description: 'لابتوب نحيف وقوي جداً مع شريحة M3 الجديدة، مثالي للطلاب والمصممين للتنقل والعمل.',
    price: 5999,
    category: 'أجهزة كمبيوتر',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800'],
    stock: 5,
    createdAt: Date.now(),
  },
  {
    id: 'p-pc-2',
    name: 'لابتوب رايزر بليد 15',
    description: 'أقوى لابتوب للألعاب بتصميم أنيق ونحيف مع كرت شاشة RTX 4080.',
    price: 9499,
    category: 'أجهزة كمبيوتر',
    images: ['https://images.unsplash.com/photo-1593642632823-8f785bc67ef7?auto=format&fit=crop&q=80&w=800'],
    stock: 3,
    createdAt: Date.now(),
  },

  // ساعات ذكية
  {
    id: '3',
    name: 'ساعة آبل الجيل التاسع',
    description: 'ساعة آبل الجديدة مع ميزات مراقبة الصحة المتقدمة، شاشة أكثر سطوعاً ومعالج S9 السريع.',
    price: 1899,
    discountPrice: 1699,
    category: 'ساعات ذكية',
    images: ['https://images.unsplash.com/photo-1544117518-30df57809ca7?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    createdAt: Date.now(),
  },
  {
    id: 'p-watch-2',
    name: 'ساعة جارمن فينيكس 7',
    description: 'الساعة المثالية للرياضيين والمغامرين مع بطارية تدوم لأسابيع وخرائط دقيقة.',
    price: 2899,
    category: 'ساعات ذكية',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    createdAt: Date.now(),
  },

  // سماعات
  {
    id: '5',
    name: 'سماعات سوني WH-1000XM5',
    description: 'أفضل سماعات إلغاء ضجيج في العالم مع جودة صوت استثنائية وبطارية تدوم طويلاً.',
    price: 1499,
    discountPrice: 1250,
    category: 'سماعات',
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    createdAt: Date.now(),
  },
  {
    id: '7',
    name: 'سماعات آير بودز برو ٢',
    description: 'تجربة صوتية محيطية مع ميزة إلغاء الضجيج النشط وبطارية محسنة.',
    price: 999,
    discountPrice: 849,
    category: 'سماعات',
    images: ['https://images.unsplash.com/photo-1588423770574-91021160dfbb?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    createdAt: Date.now(),
  },

  // ألعاب فيديو
  {
    id: 'p-game-1',
    name: 'بلايستيشن 5 سليم',
    description: 'جهاز الألعاب الأقوى من سوني بتصميم جديد أصغر حجماً وأداء مذهل.',
    price: 2299,
    discountPrice: 2099,
    category: 'ألعاب فيديو',
    images: ['https://images.unsplash.com/photo-1606813907291-d86ebb9c74ad?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    createdAt: Date.now(),
  },
  {
    id: 'p-game-2',
    name: 'نينتندو سويتش OLED',
    description: 'استمتع بألعابك المفضلة في أي مكان مع شاشة OLED زاهية الألوان.',
    price: 1599,
    category: 'ألعاب فيديو',
    images: ['https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    createdAt: Date.now(),
  },

  // إكسسوارات
  {
    id: 'p-acc-1',
    name: 'شاحن أنكر لاسلكي سريع',
    description: 'شاحن أنكر اللاسلكي السريع لشحن هاتفك بسهولة وسرعة عالية.',
    price: 199,
    discountPrice: 149,
    category: 'إكسسوارات',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    createdAt: Date.now(),
  },

  // كاميرات
  {
    id: 'p-cam-1',
    name: 'سوني A7 IV',
    description: 'كاميرا احترافية تناسب المصورين وصناع المحتوى بجودة فيديو 4K مذهلة.',
    price: 8999,
    category: 'كاميرات',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800'],
    stock: 4,
    createdAt: Date.now(),
  },
  {
    id: 'p-cam-2',
    name: 'كانون EOS R6',
    description: 'سرعة مذهلة في التركيز التلقائي وجودة صور لا تضاهى في ظروف الإضاءة الضعيفة.',
    price: 7499,
    category: 'كاميرات',
    images: ['https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&q=80&w=800'],
    stock: 6,
    createdAt: Date.now(),
  },

  // أجهزة منزلية
  {
    id: 'p-home-1',
    name: 'مكنسة دايسون V15 الذكية',
    description: 'مكنسة لاسلكية قوية بتقنية الليزر لكشف الأتربة المجهرية.',
    price: 2999,
    category: 'أجهزة منزلية',
    images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    createdAt: Date.now(),
  },
  {
    id: 'p-home-2',
    name: 'قلاية فيليبس الهوائية XXL',
    description: 'طهي صحي ومقرمش بدون زيت مع سعة كبيرة تناسب العائلة.',
    price: 1299,
    discountPrice: 899,
    category: 'أجهزة منزلية',
    images: ['https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=800'],
    stock: 18,
    createdAt: Date.now(),
  },
];
